const ul = document.querySelectorAll('ul')
const list = document.querySelectorAll('li')
// const list = document.querySelectorAll()
ul[0].prepend(list[10])
ul[0].prepend(list[2])
ul[0].prepend(list[9])
ul[0].prepend(list[7])
ul[0].prepend(list[5])
ul[0].prepend(list[4])
ul[0].prepend(list[8])
ul[0].prepend(list[6])
ul[0].prepend(list[3])
ul[0].prepend(list[1])
ul[0].prepend(list[0])

console.log(ul)
console.log(list)